var listAdjective = [
    {name: "joli", char:"きれい"},
    {name: "solide", char:"じょうぶ"},
    {name: "simple", char:"かんたん"},
    {name: "ennuyeux", char:"たいくつ"},
    {name: "libre", char:"ひま"},
    {name: "être en bonne santé", char:"げんき"},
    {name: "gai", char:"にぎやか"},
    {name: "calme", char:"しずか"},
    {name: "pratique", char:"べんり"},
    {name: "célèbre", char:"ゆうめい"},
    {name: "chic", char:"おしゃれ"},
    {name: "gentil", char:"しんせつ"},
    {name: "beau", char:"ハンサム"},

    {name: "grand", char:"おおきい"},
    {name: "petit", char:"ちいさい"},
    {name: "cher", char:"たかい"},
    {name: "bon marché", char:"やすい"},
    {name: "haut", char:"たかい"},
    {name: "bas", char:"ひくい"},
    {name: "long", char:"ながい"},
    {name: "court", char:"みじかい"},
    {name: "chaud", char:"あつい"},
    {name: "froid", char:"つめたい"},
    {name: "chaud", char:"あつい"},
    {name: "froid", char:"さむい"},
    {name: "doux", char:"あたたかい"},
    {name: "frais", char:"すずしい"},
    {name: "nouveau", char:"あたらしい"},
    {name: "vieux", char:"ふるい"},
    {name: "bon", char:"おいしい"},
    {name: "mauvais", char:"まずい"},
    {name: "rapide", char:"はやい"},
    {name: "lent", char:"おそい"},
    {name: "bon", char:"いい"},
    {name: "mauvais", char:"わるい"},
    {name: "difficile", char:"むずかしい"},
    {name: "facile", char:"やさしい"},
    {name: "intéressant", char:"おもしろい"},
    {name: "occupé", char:"いそがしい"},
    {name: "amusant", char:"たのしい"},
    {name: "sale", char:"きたない"},
    {name: "triste", char:"さびしい"},
    {name: "super", char:"すごい"}
];

